# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lr < Formula
  desc "LoginRadius CLI to support LoginRadius API's and workflow!"
  homepage "https://github.com/loginradius/lr-cli"
  version "0.3.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/LoginRadius/lr-cli/releases/download/v0.3.0/lr_0.3.0_macOS_amd64.tar.gz"
    sha256 "ffbc0ca5d37775d4eb2fed8dcf4aaac8e912abb5a71404d9c1574542ff4a4173"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/LoginRadius/lr-cli/releases/download/v0.3.0/lr_0.3.0_linux_amd64.tar.gz"
    sha256 "881ccc304a373163860d82f6bc52ee91bfc54db416115a9562f22cd02e6bc359"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/LoginRadius/lr-cli/releases/download/v0.3.0/lr_0.3.0_linux_armv6.tar.gz"
    sha256 "079ce0f2fd8bb8b19a600afffc547b92493f613f71988d434c634a3a916d5abf"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/LoginRadius/lr-cli/releases/download/v0.3.0/lr_0.3.0_linux_arm64.tar.gz"
    sha256 "9326cfe21f5498174cc793232b83bbfec29de509ed9b334ea3123e27fc06ce31"
  end

  def install
    bin.install "lr"
  end

  test do
    system "lr --help"
  end
end
