# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lr < Formula
  desc "LoginRadius CLI to support LoginRadius API's and workflow!"
  homepage "https://github.com/loginradius/lr-cli"
  version "0.4.1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/LoginRadius/lr-cli/releases/download/v0.4.1/lr_0.4.1_macOS_amd64.tar.gz"
    sha256 "ac318c3cb9fa42e1dffd2025f1b07d478f725d62aa83daf73077d1e536ebf9a9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/LoginRadius/lr-cli/releases/download/v0.4.1/lr_0.4.1_linux_amd64.tar.gz"
    sha256 "c25fe0fe2833af075245a7523487248f487e1aff70fabac797730d801b0ca7f8"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/LoginRadius/lr-cli/releases/download/v0.4.1/lr_0.4.1_linux_armv6.tar.gz"
    sha256 "78627488d7542f3a4769077b0c6fc2ce956e718ae9761be0a5ff4b758fa66cf4"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/LoginRadius/lr-cli/releases/download/v0.4.1/lr_0.4.1_linux_arm64.tar.gz"
    sha256 "26878f0ce502a033ee16ba63d61dd95cb6ab1e31a048fb8627288a53cd9eff96"
  end

  def install
    bin.install "lr"
  end

  test do
    system "lr --help"
  end
end
